nome = input('Insira seu nome: ')
nomeup = nome.upper()
nomelow = nome.lower()
print(f'Seu nome em maiúsculas é {nomeup}')
print(f'Seu nome em minúsculas é {nomelow}')
nome_sem_espacos = nome.replace(' ', '')
print(f'Seu nome tem {len(nome_sem_espacos)} letras')