nome = input('Insira seu nome: ')
nomeup = nome.upper()
nomelow = nome.lower()
print(f'Seu nome em maiúsculas é {nomeup}')
print(f'Seu nome em minúsculas é {nomelow}')
nome1 = nome.strip()
print(f'Seu nome tem {len(nome1)} caracteres (sem espaços extras)')